INDENT = " " * 4
COVER_XHTML = "_cover.xhtml"
FILES_TO_OVERWRITE = ["img/cover.jpg"]
METADATA_JSON = "_metadata.json"
NAV_JSON = "_nav.json"
NAV_XHTML = "_nav.xhtml"
PACKAGE_OPF = "package.opf"
ROOT_PATH_DIR = "OEBPS"
TEMPLATE_XHTML = "_template.xhtml"
TOC_XHTML = "_toc.xhtml"
